### PR TITLE
Fixes memory leak when channel is closed

### PR DESCRIPTION
**Pull request by mkhq**
This was fixed by @Sebruck in an old PR to finagle-libs: https://github.com/sprsquish/finagle-libs/pull/3

### CODE REVIEW

**Comment by travisbrown** [comment]
:+1: from me.

**Comment by mkhq** [comment]
@travisbrown great! Can you merge? I don't have write access.

**Comment by travisbrown** [comment]
@mkhq Now you do—want to try it out?

**Comment by mkhq** [comment]
@travisbrown thanks! It worked :)

**Comment by Sebruck** [comment]
cool, I didn't know this project is now in "finagle" :+1:

**Pull request merged**
