### PR TITLE
Drag finagle-websockets screaming into the future

### PR DESCRIPTION
**Pull request by sprsquish**
Remove dependency on Offer/Broker. Use Reader/Writer and AsyncStream instead.
Combine text and binary streams. This also leaves the door open to passing other frames to the service and handling ping/pong (and keep alive) in filters.

I think this is a decent start.

pinging @olix0r for review

### CODE REVIEW

**Comment by mkhq** [comment]
Looks great!

**Comment by luciferous** [comment]
I'll just comment on the API at the moment, hope to look deeper this weekend. I'm probably missing a lot of context, so take with a grain of salt.

`Service[WebSocket, Unit]` implies that services receive a socket type object as input and can read and write frames from it, making the output type irrelevant. This is quite a departure from Finagle services, but is it necessary? This is where I might be missing some context.

I think WebSocket services can be quite close to streaming HTTP services, which if you squint your eyes are `Service[Reader, Reader]`. Could we describe a WebSocket service as `Service[WebSocket, WebSocket]`? Where:

```
type WebSocket = AsyncStream[Message]

sealed trait Message
case class Binary(buf: Buf) extends Message
case class Text(s: String) extends Message
case object Ping extends Message
case object Pong extends Message
[...]
```

Described this way, WebSocket services look very similar to streaming HTTP services, and leverage all of the workarounds developed to get HTTP streaming to make sense in a Finagle RPC world (see: `DelayedServiceFactory`).

**Comment by sprsquish** [comment]
Yea. That's about right. Are there docs somewhere that discuss streaming http a bit more? How are streams closed? How are clients/servers notified of a close event? How are the URI and headers communicated from the client and to the server?

**Comment by luciferous** [comment]
There isn't a document explaining the architecture, but you can refer to [ChannelTransport](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/netty3/transport/ChannelTransport.scala), [HttpClientDispatcher](https://github.com/twitter/finagle/blob/develop/finagle-http/src/main/scala/com/twitter/finagle/http/codec/HttpClientDispatcher.scala), [HttpServerDispatcher](https://github.com/twitter/finagle/blob/develop/finagle-http/src/main/scala/com/twitter/finagle/http/codec/HttpServerDispatcher.scala) and [ConnectionManager](https://github.com/twitter/finagle/blob/develop/finagle-http/src/main/scala/com/twitter/finagle/http/codec/ConnectionManager.scala). The quirks are mostly just in `ConnectionManager`, but don't worry about them for now.

**Comment by luciferous** [comment]
Thinking further about this: would you like to split the work up into a client portion and server portion? I have a branch containing my thoughts for the server.

**Comment by sprsquish** [comment]
wfm

**Comment by luciferous** [comment]
@sprsquish Other than the further work on client and server PRs, is there anything left from here we want to get to for next release?

**Comment by darkfrog26** [comment]
when can we expect this to be merged?

**Comment by luciferous** [comment]
@darkfrog26 have a look at the `develop` branch which has work that this branch was a prototype for. Is there a feature you're curious about in particular?

**Pull request closed without merging**
